//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.InventoryDetails = new HashSet<InventoryDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public int employeeId { get; set; }
        public int departmentId { get; set; }
        public int statusId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual InventoryStatus InventoryStatus { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryDetail> InventoryDetails { get; set; }
    }
}
