//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDetail
    {
        public int Id { get; set; }
        public int inventoryId { get; set; }
        public int productId { get; set; }
        public int qtyInStock { get; set; }
        public int qtyActual { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Product Product { get; set; }
    }
}
