//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsList
    {
        public int Id { get; set; }
        public int vendorId { get; set; }
        public string name { get; set; }
        public string barcode { get; set; }
        public string description { get; set; }
        public Nullable<double> priceSell { get; set; }
        public Nullable<double> priceBuy { get; set; }
        public string vendorName { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
