//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetail
    {
        public int Id { get; set; }
        public int saleId { get; set; }
        public int productId { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual Product Product { get; set; }
    }
}
