//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersList
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public int statusId { get; set; }
        public int departmentId { get; set; }
        public int usertypeId { get; set; }
        public string StatusName { get; set; }
        public string TypeName { get; set; }
        public string departmentName { get; set; }
    }
}
